"""add expires_at to password reset

Revision ID: 64ab2352a002
Revises: e3a09004857f
Create Date: 2026-05-23 12:09:57.229247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ab2352a002'
down_revision = 'e3a09004857f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
