"""create password reset table

Revision ID: e3a09004857f
Revises: 6ec677905d84
Create Date: 2026-05-23 11:58:21.780271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a09004857f'
down_revision = '6ec677905d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['reset_token'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('token')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_used')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
